### ISSUE TITLE
Tab is replaced to Enter

### ISSUE THREAD

**Issue by InfSpell** [sorleone/doxtract#1]
Windows 10
Node 10.15.0

Hello, thanks for the good library.
I noticed that all \t are replaced by \n, is this how it was conceived? And you can leave a tab?

**Comment by sorleone** [comment]
Hello,

thank you very much for your comments and feedback. I think I have understood the issue, but if you could provide a minimal working example that reproduces the problem it would be very helpful (create a repository here on GitHub with the code and Office file and paste here the link). If you prefer feel free to make a pull request with the changes that you would like as well.

Sorry for the delay, but I missed the notification.

**Comment by InfSpell** [comment]
Hello,
I have done several experiments and it seems the tab characters (\t) just do not count....
```
const fs = require('fs')
const _WExtractorDocX = require('doxtract').extractText

async function foo() {
  let docX = await _WExtractorDocX('f:/lorem.docx')
  fs.writeFile('./result.json', JSON.stringify(docX, null, ' '), (err) => { console.log(err) })
}

foo()
```
input --->
Lorem\t\t ipsum dolor sit amet consectetur, adipisicing elit. Nemo hic quam provident maiores commodi illo iusto ducimus facere magnam assumenda sunt, voluptas iure quia, veritatis dolores, quasi doloribus ratione officiis. Minima harum maxime vel quia vitae, cumque tempora delectus rerum deserunt a id ullam similique earum pariatur et reprehenderit odit error in omnis,\t\t\tconsequuntur veritatis illo, dolore enim nisi! Omnis nemo odit commodi repellat culpa facere esse et, doloribus temporibus amet dicta incidunt explicabo? Odio deleniti sequi ratione, libero atque\t\t adipisci nemo. Numquam perferendis assumenda officia sapiente voluptas quam eveniet nihil, autem\t\t\t aperiam itaque aliquid quo enim quasi facilis suscipit.\n\n

output --->
Lorem ipsum dolor sit amet consectetur, adipisicing elit. Nemo hic quam provident maiores commodi illo iusto ducimus facere magnam assumenda sunt, voluptas iure quia, veritatis dolores, quasi doloribus ratione officiis. Minima harum maxime vel quia vitae, cumque tempora delectus rerum deserunt a id ullam similique earum pariatur et reprehenderit odit error in omnis,consequuntur veritatis illo, dolore enim nisi! Omnis nemo odit commodi repellat culpa facere esse et, doloribus temporibus amet dicta incidunt explicabo? Odio deleniti sequi ratione, libero atque adipisci nemo. Numquam perferendis assumenda officia sapiente voluptas quam eveniet nihil, autem aperiam itaque aliquid quo enim quasi facilis suscipit.\n\n

**Comment by InfSpell** [comment]
Shut down accidentally :)
And in some cases added (\n)

input --->
Достатньо\tобґрунтованим,\tна\tнашу\tдумку,\tє\tвизначення\n«ціноутворення»,\tщо\tнаводить\tЛ. О. Чорна,\tяка\tвизначає\tйого\tяк\n«…безперервний економічний процес формування рівня цін на товари,\nроботи і послуги, що здійснюється їх продавцем для реалізації його визначених економічних інтересів в конкретних ринкових умовах під економічним регулюванням з боку державних органів управління» [165, с.55]. З погляду вказаного автора процес ціноутворення здійснюється  з метою забезпечення економічних інтересів продавця. Дане твердження ще раз доводить, що формування ціни на підприємстві має забезпечувати його прибутковість та надходження грошових коштів в касу, або на банківські рахунки.\nВиходячи із сутності поняття «система», що відповідно до економічного словника визначається як «сукупність взаємопов'язаних між собою частин, елементів, які утворюють єдине ціле» [16, с. 501], для подальшого аналізу важливо з'ясувати складові елементи системи ціноутворення.\n\n

output --->
Достатньообґрунтованим,нанашудумку,євизначення\n\n«ціноутворення»,щонаводитьЛ. О. Чорна,якавизначаєйогояк\n\n«…безперервний економічний процес формування рівня цін на товари,\n\nроботи і послуги, що здійснюється їх продавцем для реалізації його визначених економічних інтересів в конкретних ринкових умовах під економічним регулюванням з боку державних органів управління» [165, с.55]. З погляду вказаного автора процес ціноутворення здійснюється  з метою забезпечення економічних інтересів продавця. Дане твердження ще раз доводить, що формування ціни на підприємстві має забезпечувати його прибутковість та надходження грошових коштів в касу, або на банківські рахунки.\n\nВиходячи із сутності поняття «система», що відповідно до економічного словника визначається як «сукупність взаємопов’язаних між собою частин, елементів, які утворюють єдине ціле» [16, с. 501], для подальшого аналізу важливо з’ясувати складові елементи системи ціноутворення.\n\n"

**Comment by sorleone** [comment]
Check out the latest commit and let me know how it works. I will publish it on npm after your testing.

**Comment by InfSpell** [comment]
Hello,
I tested the last commit, tabs remain and that's fine :) But I think it’s better to leave the line feed characters in the previous version (if I understood correctly now they just turn into one), I think it will be better if someone tokenizes the result. Thank you for your time!

**Comment by sorleone** [comment]
Okay I fixed everything and I will publish
