### ISSUE TITLE
add toLowerCase() to extensionRegex.test()

### ISSUE THREAD

**Issue by infFenrir** [sorleone/doxtract#2]
Otherwise files with an extension 'example.DOCX' cause an error :)
```
if (!extensionRegex.test(extname(path))) {
  reject(new Error('The file must be either a .docx, .xlsx or .pptx'));
}
```
```
if (!extensionRegex.test(extname(path).toLowerCase())) {
  reject(new Error('The file must be either a .docx, .xlsx or .pptx'));
}
```
Thank you for your library...
And didn't you think to add the ability to read from the buffer

**Comment by sorleone** [comment]
@InfSpell Good catch, I will add that. Thank you for the code and for utilizing it. I am not using this library myself at the moment, so I am not thinking about it much but it could be a good addition yes. Do you also have the code for this new feature as well?

**Comment by infFenrir** [comment]
Not yet, but when I will definitely write...
